int _putchar(char);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int x);
int _isalpha(int x);
int print_sign(int x);
int _abs(int x);
int print_last_digit(int x);
void jack_bauer(void);
void times_table(void);
int add(int num, int num2);
void print_to_98(int x);
void print_times_table(int x);
